//! Link-time capability registry for ix skills.
//!
//! Each function annotated with `#[ix_skill(...)]` emits a [`SkillDescriptor`]
//! submitted to the [`IX_SKILLS`] distributed slice. The slice is populated at
//! link time — no runtime registration calls, no central list to maintain.
//!
//! Downstream surfaces — CLI (`ix-skill`), MCP server (`ix-agent`), visual
//! editor (`ix-demo`) — all read from the same slice, guaranteeing that every
//! skill is discoverable through every interface.
//!
//! ## Windows LLD workaround
//!
//! The [`IX_SKILLS`] slice ships with a `_SENTINEL` element to avoid the
//! empty-slice LLD relocation bug ([linkme#70], [linkme#114]) on Windows MSVC.
//! All public APIs filter the sentinel out, so consumers never see it.
//!
//! [linkme#70]: https://github.com/dtolnay/linkme/issues/70
//! [linkme#114]: https://github.com/dtolnay/linkme/issues/114

use ix_types::{SocketType, Value};
use linkme::distributed_slice;
use std::collections::HashMap;
use std::sync::OnceLock;
use thiserror::Error;

// Re-export linkme so the proc-macro can reference a stable path.
pub use linkme;

/// Handler signature for every skill. Takes a slice of universally-typed
/// [`Value`]s and returns a single [`Value`] (use `Value::Null` for unit).
pub type SkillFn = fn(&[Value]) -> Result<Value, SkillError>;

/// A single input or output socket of a skill.
#[derive(Debug, Clone)]
pub struct Socket {
    pub name: &'static str,
    pub ty: SocketType,
    pub optional: bool,
    pub doc: &'static str,
}

/// Metadata + handler for one skill. Constructed at compile time by the
/// `#[ix_skill]` proc-macro and submitted to the [`IX_SKILLS`] slice.
#[derive(Debug, Clone)]
pub struct SkillDescriptor {
    /// Dotted fully-qualified name — e.g. `"supervised.linear_regression.fit"`.
    pub name: &'static str,
    /// Domain tag — e.g. `"supervised"`, `"signal"`, `"governance"`.
    pub domain: &'static str,
    /// Name of the crate the skill lives in.
    pub crate_name: &'static str,
    /// Doc comment harvested from the annotated fn.
    pub doc: &'static str,
    pub inputs: &'static [Socket],
    pub outputs: &'static [Socket],
    /// Governance tags — e.g. `["empirical", "deterministic"]`.
    pub governance_tags: &'static [&'static str],
    /// Lazy JSON-schema emitter (called once, memoized downstream).
    pub json_schema: fn() -> serde_json::Value,
    /// Lazy OUTPUT JSON-schema emitter — the field names/types the skill emits,
    /// so a pipeline proposer can reference them in a downstream `{"from":
    /// "stage.field"}`. Returns `Value::Null` when the skill does not declare an
    /// output schema (the default); consumers treat Null as "undeclared".
    pub output_schema: fn() -> serde_json::Value,
    /// The adapter fn generated by the macro.
    pub fn_ptr: SkillFn,
}

/// The distributed slice populated at link time by every `#[ix_skill]`
/// annotation across the workspace.
#[distributed_slice]
pub static IX_SKILLS: [SkillDescriptor] = [..];

/// Windows LLD empty-slice workaround. All public APIs filter this out.
#[distributed_slice(IX_SKILLS)]
static _SENTINEL: SkillDescriptor = SkillDescriptor {
    name: "__sentinel__",
    domain: "__internal__",
    crate_name: "ix-registry",
    doc: "",
    inputs: &[],
    outputs: &[],
    governance_tags: &[],
    json_schema: sentinel_schema,
    output_schema: sentinel_output_schema,
    fn_ptr: sentinel_fn,
};

fn sentinel_schema() -> serde_json::Value {
    serde_json::json!({})
}
fn sentinel_output_schema() -> serde_json::Value {
    serde_json::Value::Null
}
fn sentinel_fn(_: &[Value]) -> Result<Value, SkillError> {
    Err(SkillError::NotFound("__sentinel__".into()))
}

/// Errors returned by skill invocation + lookup.
#[derive(Debug, Error)]
pub enum SkillError {
    #[error("skill not found: {0}")]
    NotFound(String),

    #[error("arity mismatch: expected {expected}, got {actual}")]
    Arity { expected: usize, actual: usize },

    #[error("type error on arg {arg_index}: {source}")]
    Type {
        arg_index: usize,
        #[source]
        source: ix_types::TypeError,
    },

    #[error("execution failed: {0}")]
    Exec(String),

    #[error("remote federation error: {0}")]
    Remote(String),
}

impl From<ix_types::TypeError> for SkillError {
    fn from(e: ix_types::TypeError) -> Self {
        SkillError::Type {
            arg_index: 0,
            source: e,
        }
    }
}

// ---------------------------------------------------------------------------
// Public lookup API. All methods filter out the sentinel.
// ---------------------------------------------------------------------------

static INDEX: OnceLock<HashMap<&'static str, &'static SkillDescriptor>> = OnceLock::new();

fn index() -> &'static HashMap<&'static str, &'static SkillDescriptor> {
    INDEX.get_or_init(|| {
        IX_SKILLS
            .iter()
            .filter(|s| s.name != "__sentinel__")
            .map(|s| (s.name, s))
            .collect()
    })
}

/// Look up a skill by its dotted name.
pub fn by_name(name: &str) -> Option<&'static SkillDescriptor> {
    index().get(name).copied()
}

/// Every skill in a given domain (e.g. `"supervised"`).
pub fn by_domain(domain: &str) -> Vec<&'static SkillDescriptor> {
    index()
        .values()
        .copied()
        .filter(|s| s.domain == domain)
        .collect()
}

/// Substring search across names + doc strings.
pub fn search(query: &str) -> Vec<&'static SkillDescriptor> {
    let q = query.to_lowercase();
    index()
        .values()
        .copied()
        .filter(|s| s.name.to_lowercase().contains(&q) || s.doc.to_lowercase().contains(&q))
        .collect()
}

/// Iterator over all registered skills (sentinel filtered).
pub fn all() -> impl Iterator<Item = &'static SkillDescriptor> {
    index().values().copied()
}

/// Number of registered skills (sentinel filtered).
pub fn count() -> usize {
    index().len()
}

/// Invoke a skill by name. Routes to the local `fn_ptr` by default; remote
/// federation dispatch (TARS / GA via MCP) is reserved for a future module.
pub fn invoke(name: &str, args: &[Value]) -> Result<Value, SkillError> {
    match by_name(name) {
        Some(desc) => (desc.fn_ptr)(args),
        None => Err(SkillError::NotFound(name.into())),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sentinel_is_filtered_from_public_api() {
        // The sentinel element never appears in public iteration.
        assert!(all().all(|s| s.name != "__sentinel__"));
        assert!(by_name("__sentinel__").is_none());
    }

    #[test]
    fn invoke_unknown_skill_returns_not_found() {
        let err = invoke("does.not.exist", &[]).unwrap_err();
        assert!(matches!(err, SkillError::NotFound(_)));
    }
}
