//! Markdown report renderer for executive / CI consumption.

use crate::coverage::{CoverageMatrix, OptimalityVerdict};
use crate::invariant::InvariantStatus;

pub fn render_markdown(matrix: &CoverageMatrix) -> String {
    let report = matrix.report();
    let (invariants, exemplars) = report.shape;

    let mut out = String::new();
    out.push_str("# Invariant coverage report\n\n");
    out.push_str(&format!(
        "Matrix: **{invariants} invariants × {exemplars} exemplars** (rank = **{}**).\n\n",
        report.rank
    ));

    let verdict_line = match report.verdict {
        OptimalityVerdict::Optimal => "✔ **Optimal** — full rank, no orphans, no gaps, no duplicate rows.",
        OptimalityVerdict::Suboptimal => "✘ **Suboptimal** — see details below.",
        OptimalityVerdict::NoEvidence => "○ **No evidence** — firings JSON contained no exemplars; run the invariant tests first.",
    };
    out.push_str(verdict_line);
    out.push_str("\n\n");

    // Rank deficiency: rows exceed rank → some invariant is a linear combination.
    if report.rank < invariants && exemplars > 0 {
        let deficit = invariants - report.rank;
        out.push_str(&format!(
            "## Rank deficiency: {deficit}\n\n\
             {deficit} invariant(s) are linearly dependent on the others over GF(2). \
             At least one can be removed (or derived) without losing discriminating power.\n\n"
        ));
    }

    if !report.redundancy_pairs.is_empty() {
        out.push_str("## Strict duplicates\n\n");
        out.push_str(
            "Invariant pairs with identical firing signatures — first candidates for removal.\n\n",
        );
        out.push_str("| Keep | Remove / redefine |\n|---|---|\n");
        for (a, b) in &report.redundancy_pairs {
            out.push_str(&format!("| #{a} | #{b} |\n"));
        }
        out.push('\n');
    }

    if !report.orphan_invariants.is_empty() {
        out.push_str("## Orphan invariants (no firings observed)\n\n");
        out.push_str("| # | Domain | Status | Description |\n|---|---|---|---|\n");
        for id in &report.orphan_invariants {
            if let Some(inv) = matrix.invariants.iter().find(|i| i.id == *id) {
                out.push_str(&format!(
                    "| {} | {} | {} | {} |\n",
                    inv.id,
                    inv.domain,
                    inv.status.short(),
                    truncate(&inv.description, 80),
                ));
            }
        }
        out.push('\n');

        if !report.orphan_invariants_claimed_tested.is_empty() {
            out.push_str("### Worst case: tested but never fired\n\n");
            out.push_str(
                "These carry status `T` (tested) but observed zero firings. \
                 Either the test is vacuous or no exemplar exercises it.\n\n",
            );
            for id in &report.orphan_invariants_claimed_tested {
                out.push_str(&format!("- #{id}\n"));
            }
            out.push('\n');
        }
    }

    if !report.coverage_gaps.is_empty() {
        out.push_str("## Coverage gaps (exemplars no invariant catches)\n\n");
        for gap in &report.coverage_gaps {
            out.push_str(&format!("- `{gap}`\n"));
        }
        out.push('\n');
    }

    out.push_str("## Catalog summary by status\n\n");
    let mut tested = 0;
    let mut claimed = 0;
    let mut latent = 0;
    let mut failing = 0;
    for inv in &matrix.invariants {
        match inv.status {
            InvariantStatus::Tested => tested += 1,
            InvariantStatus::Claimed => claimed += 1,
            InvariantStatus::Latent => latent += 1,
            InvariantStatus::Failing => failing += 1,
        }
    }
    out.push_str(&format!("- Tested (T): {tested}\n"));
    out.push_str(&format!("- Claimed but untested (C): {claimed}\n"));
    out.push_str(&format!("- Latent / not claimed (N): {latent}\n"));
    out.push_str(&format!("- Known failing (FAIL): {failing}\n\n"));

    out.push_str("---\n");
    out.push_str("_Generated by `ix-invariant-coverage`._\n");
    out
}

fn truncate(s: &str, max: usize) -> String {
    if s.chars().count() <= max {
        s.to_string()
    } else {
        let mut end = 0;
        for (i, _) in s.char_indices().take(max) {
            end = i;
        }
        format!("{}…", &s[..end])
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::coverage::{Exemplar, Firings};
    use crate::invariant::Invariant;
    use std::collections::BTreeMap;

    #[test]
    fn optimal_matrix_renders_clean_verdict() {
        let invs = vec![Invariant {
            id: 1,
            domain: "test".into(),
            description: "simple".into(),
            artifact: "a".into(),
            status: InvariantStatus::Tested,
        }];
        let mut fired = BTreeMap::new();
        fired.insert(1, ["x"].into_iter().map(String::from).collect());
        let firings = Firings {
            exemplars: vec![Exemplar {
                id: "x".into(),
                description: "x".into(),
                kind: "Synthetic".into(),
            }],
            fired,
        };
        let md = render_markdown(&CoverageMatrix::new(invs, firings));
        assert!(md.contains("Optimal"));
        assert!(md.contains("1 invariants × 1 exemplars"));
    }

    #[test]
    fn suboptimal_matrix_shows_gaps() {
        let invs = vec![Invariant {
            id: 1,
            domain: "test".into(),
            description: "simple".into(),
            artifact: "a".into(),
            status: InvariantStatus::Tested,
        }];
        let firings = Firings {
            exemplars: vec![Exemplar {
                id: "uncaught".into(),
                description: "uncaught".into(),
                kind: "Synthetic".into(),
            }],
            fired: BTreeMap::new(),
        };
        let md = render_markdown(&CoverageMatrix::new(invs, firings));
        assert!(md.contains("Suboptimal"));
        assert!(md.contains("Coverage gaps"));
        assert!(md.contains("uncaught"));
    }
}
