import json, random
B = "boundary"
data = {
 "skill.chordinfo": [
  ("whats actually in a cmaj7 like which notes", []),
  ("how do i finger an F#m7b5 without my hand dying lol", []),
  ("sus2 vs sus4 whats the diff, soundwise and notes wise", []),
  ("teacher wrote E7#9 on my sheet wtf is that chord", []),
  ("what makes a chord diminished exactly? like the dim one built on B, whats going on inside it", [B]),
  ("need the notes in a Bb chord, the song im learning is in F", [B]),
  ("saw someone on a jazz forum call a chord C6/9, spell it out for me pls", []),
 ],
 "skill.scaleinfo": [
  ("notes in e minor pentatonic?", []),
  ("how do i play the blues scale in A, the one evryone uses for solos", ["typo"]),
  ("harmonic minor... what is it? sounds all egyptian lol", []),
  ("whats the whole/half step pattern for the major scale i always forget it", []),
  ("been playing 2 years mostly strumming chords, want to start soloing over stuff in G. what notes am i even allowed to hit", [B, "long"]),
  ("melodic minor going up vs coming down, is that still a thing on guitar or just classical piano people", []),
  ("whats the minor pentatonic box that fits over a C major song, which fret do i start", [B]),
 ],
 "skill.modes": [
  ("can someone explain modes like im 5. every youtube vid loses me right after ionian", ["beginner"]),
  ("lydian = major with a #4 right? why does it sound so dreamy", []),
  ("mixolydian over a one chord dominant vamp, which notes do i lean on", []),
  ("aeolian vs natural minor, is it literally the same thing or am i missing something", []),
  ("if im in D dorian am i just playing C major notes?? then whats even the point", [B]),
  ("phrygian dominant vs regular phrygian, whats the one note difference", []),
  ("which mode is the darkest one? want that evil sound for riffs", [B]),
 ],
 "skill.interval": [
  ("how many frets is a perfect fifth", []),
  ("C up to Ab, is that a minor 6th or an aug 5th, how do u tell", []),
  ("tritone = devils interval yeah? where is it on the neck", []),
  ("ear training q: how do i hear the diff between a major 3rd and a minor 3rd", []),
  ("from G up to E what do you call that distance", []),
  ("why do power chords only use root and fifth, whats a fifth exactly in terms of notes apart", [B]),
  ("slid from 5th fret to 8th fret same string, what interval did i just play", []),
 ],
 "skill.chordsubstitution": [
  ("whats a cooler chord to swap in instead of plain G7 going to C", []),
  ("tritone sub explained pls, so Db7 instead of G7??", []),
  ("my progression is C Am F G and the F is boring, can i replace it with something jazzier that still does the same job", [B]),
  ("reharm ideas for a 2-5-1, i always just play dm7 g7 cmaj7 straight", []),
  ("can i play Em instead of C somewhere in a song? i heard they basically overlap", [B]),
  ("anything i can use in place of B7 that fills the same role? not about difficulty, just want more color", []),
  ("relative minor sub, when does it work and when does it sound wrong", []),
 ],
 "skill.beginnerchords": [
  ("just got my first guitar, what chords should i learn first", ["beginner"]),
  ("F barre is impossible for me, is there an easier way to play F for now", [B]),
  ("whats the easiest chords to start with so i can play some campfire songs", ["beginner"]),
  ("3 weeks in, my fingers cant reach for G, any simpler shape", ["beginner"]),
  ("open chords every newbie should know?", []),
  ("my kid is 8 and just started, which chords are small-hand friendly", ["long"]),
  ("teach me like 4 easy chords so i can strum along to pop songs", [B]),
 ],
 "skill.progressionmood": [
  ("i have G D Em C and want it to sound sadder, what do i change", []),
  ("make this less happy: C F G C", []),
  ("Am F C G feels too emo, how do i brighten it up without wrecking the vibe", []),
  ("want my verse Dm Bb F C to go darker, like horror movie ominous", []),
  ("can i drop a Fm into my C major progression to make it more bittersweet? where would it go", [B]),
  ("how can i make E A B feel more hopeful for the chorus, it's kinda flat rn", []),
  ("my chords Em C G D sound too gloomy, can i keep the same roots and flip it to feel warmer", [B]),
 ],
 "skill.circleoffifths": [
  ("how do i actually use that circle poster thing, i have it on my wall and no clue", ["beginner"]),
  ("what key has 4 sharps", []),
  ("why does the order of sharps go F C G D A E B, is there a trick", []),
  ("which keys are next door to D on the wheel", []),
  ("relative minor of Eb major?", [B]),
  ("is going counterclockwise around the circle the same as going up a fourth each step", [B]),
  ("how many flats in Ab and which ones", []),
 ],
 "skill.practiceroutine": [
  ("i get like 30 min a day after work, how should i split it up", []),
  ("been playing 2 years and im stuck, i just noodle the same pentatonic licks every night. need some kind of structure to actually get better", ["long"]),
  ("whats a good weekly plan to get my chord changes faster", []),
  ("how long should a beginner practice per day, my fingers hurt after 15 min", ["beginner"]),
  ("want to learn all 7 modes this month, can you lay out a day by day schedule", [B]),
  ("warmup stuff before a gig? 10 minutes max", []),
  ("want to get into jazz, how do i organize my practice time over the next 3 months", [B]),
 ],
 "skill.genreessentials": [
  ("what should i learn first if i wanna play blues", []),
  ("getting into bossa nova, what chords and rhythms are must knows", []),
  ("whats the core toolkit for country guitar, chicken pickin and all that", []),
  ("metal rhythm guitar basics? what scales and shapes do metal guys actually use", []),
  ("funk guitar, what makes it sound funky? my stuff sounds like strumming", []),
  ("what chords do i need for punk, is it seriously just power chords", [B]),
  ("neo soul chords are so pretty, whats the vocab i need to sound like that", [B]),
 ],
 "skill.whatcanyoudo": [
  ("what can you help me with", []),
  ("hi new here, what kind of stuff do you know", ["beginner"]),
  ("are you able to write tabs or just theory stuff", [B]),
  ("can u do anything besides chords", []),
  ("list your features", []),
  ("so like... what am i supposed to ask you", []),
  ("do you handle bass or uke too or only guitar", [B]),
 ],
 "skill.transpose": [
  ("song is E A B but i cant sing that high, need it in D", []),
  ("capo on 3 playing G shapes, what are the actual chords im sounding", [B]),
  ("put Am F C G up a whole step pls", []),
  ("singer wants it 2 half steps lower: Bb Gm Eb F", []),
  ("i know this tune in C but the recording is in Eb, whats the chart there", []),
  ("how do i shift a progression to a different key without doing math every time", [B]),
  ("band plays in standard but i'm tuned down a half step, what do my chords become so i match them", []),
 ],
 "skill.commontones": [
  ("which notes do C and Am share", []),
  ("whats in common between G and Em7", []),
  ("going from D to Bm, which note can i leave ringing", []),
  ("F to Dm7 shared notes?", []),
  ("want smooth voice leading from Cmaj7 to Fmaj7, which tones can stay put", [B]),
  ("do E and C have any notes in common at all", []),
  ("writing a drone part under two chords, what notes are in both A and D", [B]),
 ],
 "skill.diatonicchords": [
  ("what chords are in the key of G", []),
  ("chords that work in D major?", []),
  ("list the 7 chords in e minor pls", []),
  ("why is the 7th chord diminished in every major key, like which one is it in C", [B]),
  ("whats the 1 4 5 in A", []),
  ("which 7th chords belong to Bb major", []),
  ("playing in F, should i use a Bb or a B chord, which one fits", [B]),
 ],
 "skill.keyidentification": [
  ("what key is G Em C D", []),
  ("song goes Am Dm E Am, what key is that", []),
  ("chords are F#m D A E, is that A major or F# minor", []),
  ("trying to jam over Bb F Gm Eb, what key do i solo in", [B]),
  ("C D Em G what key am i in lol", []),
  ("song uses B E F# and C#m, whats the key", []),
  ("is Dm G C in C major or D dorian", [B]),
 ],
 "skill.progressioncompletion": [
  ("C G Am ... what comes next", []),
  ("i have Em C G, need a 4th chord", []),
  ("stuck after Dm7 G7, where do i go", []),
  ("writing a song: A E F#m and then? want it to resolve", []),
  ("what chord should end this: F G Em Am ...", []),
  ("good chord to lead back into the start of my G C D loop", [B]),
  ("Am G F... then E or something? what sounds natural there", [B]),
 ],
 "__none__": [
  ("whats a good amp under 500 for bedroom playing", ["oos"]),
  ("tube screamer vs klon clone which one", ["oos"]),
  ("tab for the hotel california solo?", ["oos", B]),
  ("can you give me the chords to wonderwall", ["oos", B]),
  ("how do i copyright my song before putting it on spotify", ["oos", B]),
  ("help me write lyrics about my ex", ["oos"]),
  ("who invented the electric guitar", ["oos"]),
  ("whats the weather in nashville tomorrow", ["oos"]),
  ("write me a python script that tunes my guitar from the mic", ["oos"]),
  ("whats 17 times 23", ["oos"]),
  ("should i buy a strat or a tele", ["oos"]),
  ("how often should i change strings", ["oos"]),
  ("how much should i charge for a wedding gig", ["oos", B]),
  ("lol my cat just knocked my guitar off the stand", ["oos"]),
  ("when did the beatles put out abbey road", ["oos"]),
  ("best string gauge for drop c", ["oos"]),
 ],
}
items = [(p, l, t) for l, v in data.items() for p, t in v]
assert len(items) == 128, len(items)
assert len(set(p for p, _, _ in items)) == 128
random.Random(20260923).shuffle(items)
out = {"version": "fresh-claude-1", "authoredBy": "claude-subagent-blind",
       "prompts": [{"id": f"f-{i+1}", "prompt": p, "expectedIntentId": l, "tags": t} for i, (p, l, t) in enumerate(items)]}
path = r"C:\Users\spare\AppData\Local\Temp\claude\C--Users-spare-source-repos-ix\16f62590-0d0a-4ded-9ff5-65b291b83d23\scratchpad\fresh-test.json"
with open(path, "w", encoding="utf-8") as f:
    json.dump(out, f, indent=1, ensure_ascii=False)
from collections import Counter
print(Counter(l for _, l, _ in items))
print(sum(1 for _, _, t in items if B in t))
